import json
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, OWL
import urllib.parse

def main():
    # Define our custom namespace
    ONTO = Namespace("http://credit-analysis.org/ontology/")

    # Initialize the graph
    g = Graph()
    g.bind("onto", ONTO)

    # Load the JSON knowledge graph generated by build_kb.py
    try:
        with open("knowledge_graph.json", "r", encoding="utf-8") as f:
            kg = json.load(f)
    except FileNotFoundError:
        print("Error: knowledge_graph.json not found.")
        return

    print(f"Loaded {len(kg.get('nodes', []))} nodes and {len(kg.get('edges', []))} edges from JSON.")

    # Process Nodes
    for node in kg.get("nodes", []):
        node_id = str(node.get("id"))
        node_type = str(node.get("type"))
        label = str(node.get("label", ""))

        # Create a safe URI for the node
        safe_id = urllib.parse.quote(node_id, safe='')
        node_uri = URIRef(ONTO[safe_id])

        # Assign class based on type (File, Chunk, Concept)
        class_uri = URIRef(ONTO[node_type])
        g.add((node_uri, RDF.type, class_uri))
        g.add((node_uri, RDF.type, OWL.NamedIndividual)) # It's an instance

        # Add label
        if label:
            g.add((node_uri, RDFS.label, Literal(label)))

        # Add subtype if present (e.g., text, perspective, definition)
        subtype = node.get("subtype")
        if subtype:
             # We could create a data property for this, but for simplicity, let's just use rdfs:comment or a custom string property
             g.add((node_uri, ONTO.hasSubtype, Literal(subtype)))


    # Process Edges
    for edge in kg.get("edges", []):
        source_id = str(edge.get("source"))
        target_id = str(edge.get("target"))
        edge_type = str(edge.get("type")).lower() # e.g., CONTAINS -> contains

        safe_source = urllib.parse.quote(source_id, safe='')
        safe_target = urllib.parse.quote(target_id, safe='')

        source_uri = URIRef(ONTO[safe_source])
        target_uri = URIRef(ONTO[safe_target])
        property_uri = URIRef(ONTO[edge_type])

        g.add((source_uri, property_uri, target_uri))

    # Serialize to TTL
    output_file = "knowledge_triples.ttl"
    g.serialize(destination=output_file, format="turtle")
    print(f"Successfully generated {output_file} with {len(g)} triples.")

if __name__ == "__main__":
    main()
